language: python

python:
-"3.6"
-"3.7"

before_install:
- openssl aes-256-cbc -K $encrypted_3fb15ced9c51_key -iv $encrypted_3fb15ced9c51_iv
  -in tagmanager_token.dat.enc -out tagmanager_token.dat -d
- openssl aes-256-cbc -K $encrypted_3fb15ced9c51_key -iv $encrypted_3fb15ced9c51_iv
  -in gcp-client.json.enc -out gcp-client.json -d
