language: python
python: "3.6"
before_install:
  - openssl aes-256-cbc -K $encrypted_3fb15ced9c51_key -iv $encrypted_3fb15ced9c51_iv -in tagmanager_token.dat.enc -out tagmanager_token.dat -d
  - openssl aes-256-cbc -K $encrypted_662a9add1c4f_key -iv $encrypted_662a9add1c4f_iv -in gcp-client.json.enc -out gcp-client.json -d
  - pip install coveralls
  - pip install pytest-cov
  - pip install pytest
install: 
  - pip install -r requirements.txt
script:
  - pytest --cov=tests/
after_success:
  - coveralls 