language: python
python: "3.7"

before_install:
  - openssl aes-256-cbc -K $encrypted_5880cf525281_key -iv $encrypted_5880cf525281_iv -in auth.tar.enc -out auth.tar -d
  - tar xvf auth.tar
  - pip install coveralls
  - pip install pytest
  - pip install pytest-cov

install:
  - pip install -r requirements.txt

script:
  - pytest --cov=analytics/

after_success:
- coveralls